### ISSUE TITLE
c++: error: unrecognized command line option '-showme'

### ISSUE THREAD

**Issue by Oneplus** [tarowatanabe/trance#1]
Dr. Watanabe

I found that `./configure` will leave this error when mpich2 instead of openmpi is installed. An investigation found that openmpi use `-showme` option while mpich2 use `-show`. http://stackoverflow.com/questions/11312719/how-to-compile-mpi-with-gcc

such difference will lead to an error in `#include <mpi.h>`. thus, mpi-related configuration in configure.ac should be treated differently between `openmpi` and `mpich2`.

**Comment by tarowatanabe** [comment]
Thanks for your report. Unfortunately, I do not have any access to mpich2 and as noted in BUILD.rst, openmpi is the only supported MPI implementation. And probably it will be difficult to differentiate -show and/or -showme, since they are MPI implementation dependent.

The configure script will ignore MPI if none of mpicc etc. exists in the executable paths. Or, probably I can add --enable-mpi option to the configure script to ignore any MPI implementation.

**Comment by tarowatanabe** [comment]
I find that -show works for openmpi, and use it instead in the configure.ac. Thanks again!

**Comment by prabhleenchhibber** [comment]
I am getting the below error in make and am unable to solve it.
bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -ftemplate-depth=1024   -o binarize_main binarize_main.o libtrance.la  -lboost_program_options -lrt 
libtool: link: g++ -g -O2 -ftemplate-depth=1024 -o .libs/binarize_main binarize_main.o  ./.libs/libtrance.so -lboost_program_options -lrt -pthread
/usr/bin/ld: binarize_main.o: undefined reference to symbol '_ZN5boost11this_thread5yieldEv'
//usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:773: recipe for target 'binarize_main' failed
make[1]: *** [binarize_main] Error 1
make[1]: Leaving directory '/home/cse587/Desktop/cl/trance-master/trance'
Makefile:454: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by tarowatanabe** [comment]
I haven't compiled it for long, but the problem sounds like a missing link to a particular library, i.e., boost_thread in this case. I think adding -lboost_thread during linking will solve the problem.
