### ISSUE TITLE
configure: error: cannot find the flags to link with Boost program_options

### ISSUE THREAD

**Issue by hour** [tarowatanabe/trance#2]
Dear Prof. @tarowatanabe 

When I ran
```
./autogen.sh
./configure --with-boost=../boost/boost_1_73_0/`
```

I've got errors
```
...
checking for Boost headers version >= 1.42.0... ../boost/boost_1_73_0//include/boost-1_73
checking for Boost's header version... 1_73
checking for the toolset name used by Boost for g++... gcc48 -gcc
checking boost/program_options.hpp usability... yes
checking boost/program_options.hpp presence... yes
checking for boost/program_options.hpp... yes
checking for the Boost program_options library... no
configure: error: cannot find the flags to link with Boost program_options
```

I am actually naive with C compilation.

Can you help me to pass this step?
Did I miss something?

My environment is
OS: CentOS 6.7
GCC 4.8.5
Boost 1.73.0
Openmpi 4.0.4

Best regards

**Comment by tarowatanabe** [comment]
I think the problem is that it is unable to fine already built boost libraries. Here is an instruction.

https://www.boost.org/doc/libs/1_73_0/more/getting_started/unix-variants.html#easy-build-and-install

Alternatively, you can install required libraries by homebrew (at brew.sh) which also supports linux.

**Comment by hour** [comment]
Thank you and sorry for late response. 

I followed the instruction in boost website but still get the same errors.

I think it cause by GCC version because I get rid of this error by simply update GCC to 5.2.0.

I will close this issue.
